name: input_validate
description: A pure Dart package for validating nested map data structures with wildcard support.
version: 1.0.1
homepage: https://github.com/vfiruz97/input-validate
repository: https://github.com/vfiruz97/input-validate
issue_tracker: https://github.com/vfiruz97/input-validate/issues
topics: [input-validation, data-validation, map-validation, form-validation]
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
